services:
  lnibackupsbot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lnibackupsbot
    restart: unless-stopped
    volumes:
      - ./backups:/app/node_modules/discord-backup/lib/backups

